<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Management frequency and extinction risk • GMSE</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><meta property="og:title" content="Management frequency and extinction risk">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">GMSE</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.4.0.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/GMSE.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/SI1.html">The Genetic Algorithm of GMSE</a>
    </li>
    <li>
      <a href="../articles/SI2.html">Use of the gmse_apply function</a>
    </li>
    <li>
      <a href="../articles/SI3.html">Example case study in GMSE</a>
    </li>
    <li>
      <a href="../articles/SI4.html">Advanced case study options</a>
    </li>
    <li>
      <a href="../articles/SI5.html">Fisheries example integrating FLR</a>
    </li>
    <li>
      <a href="../articles/SI6.html">Management frequency and extinction risk</a>
    </li>
    <li>
      <a href="../articles/SI7.html">Default GMSE data structures</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../../notebook/gmse_notes.html">Lab notebook</a>
</li>
<li>
  <a href="https://github.com/bradduthie/GMSE">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Management frequency and extinction risk</h1>
            <h3 class="subtitle">GMSE: an R package for generalised management strategy evaluation (Supporting Information 6)</h3>
                        <h4 class="author">A. Bradley Duthie¹³, Jeremy J. Cusack¹, Isabel L. Jones¹, Jeroen Minderman¹, Erlend B. Nilsen², Rocío A. Pozo¹, O. Sarobidy Rakotonarivo¹, Bram Van Moorter², and Nils Bunnefeld¹</h4>
            
            <h4 class="date">[1] Biological and Environmental Sciences, University of Stirling, Stirling, UK [2] Norwegian Institute for Nature Research, Trondheim, Norway [3] <a href="mailto:alexander.duthie@stir.ac.uk">alexander.duthie@stir.ac.uk</a>
</h4>
      
      
      <div class="hidden name"><code>SI6.Rmd</code></div>

    </div>

    
    
<div id="the-individual-based-approach-of-default-gmse-sub-models" class="section level1">
<h1 class="hasAnchor">
<a href="#the-individual-based-approach-of-default-gmse-sub-models" class="anchor"></a>The individual-based approach of default GMSE sub-models</h1>
<p>The default sub-models of GMSE (<code>resource</code>, <code>observation</code>, <code>manager</code>, <code>user</code>) are individual-based (also called ‘agent-based’), meaning that they model discrete individuals (resources or agents), which in GMSE are represented by individual table rows (as in <code>RESOURCES</code>, <code>AGENTS</code>, and <code>OBSERVATION</code>) or layers of three-dimensional arrays (as in <code>COST</code> and <code>ACTION</code>). Individual-based models (IBMs) have been a useful approach in ecology for decades <span class="citation">(Uchmański and Grimm <a href="#ref-Uchmanski1996">1996</a>; V. Grimm <a href="#ref-Grimm1999">1999</a>)</span>, providing both a pragmatic tool for the mechanistic modelling of complex populations and a powerful technique for theoretical investigation. A key advantage of the individual-based modelling approach is the discrete nature of individuals, which allows for detailed trait variation and complex interactions among individuals. In GMSE, some of the most important traits for resources include types, ages, demographic parameter values, locations, etc., and for agents (manager and users), traits include different types, utilities, budgets, etc. The traits that resources and managers have can potentially affect their interactions, and default GMSE sub-models take advantage of this by simulating interactions explicitly on a landscape (see <a href="SI7.pdf">SI7</a> for an introduction to GMSE default data structures).</p>
</div>
<div id="replicate-simulations-as-a-tool-for-model-inference" class="section level1">
<h1 class="hasAnchor">
<a href="#replicate-simulations-as-a-tool-for-model-inference" class="anchor"></a>Replicate simulations as a tool for model inference</h1>
<p>Mechanistically modelling complex interactions among discrete individuals typically causes some degree of stochasticity in IBMs (in the code, this is caused by the sampling of random values, which determine probabilistically whether or not events such as birth or death occur for individuals), reflecting the uncertainty that is inherent to complex systems. We can see a simple example of this by calling <code>gmse_apply</code> under the same default conditions twice.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_eg_1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_apply.html">gmse_apply</a></span>();
<span class="kw">print</span>(rand_eg_1);</code></pre></div>
<pre><code>## $resource_results
## [1] 1082
## 
## $observation_results
## [1] 1020.408
## 
## $manager_results
##          resource_type scaring culling castration feeding help_offspring
## policy_1             1      NA      62         NA      NA             NA
## 
## $user_results
##         resource_type scaring culling castration feeding help_offspring
## Manager             1      NA       0         NA      NA             NA
## user_1              1      NA      16         NA      NA             NA
## user_2              1      NA      16         NA      NA             NA
## user_3              1      NA      16         NA      NA             NA
## user_4              1      NA      16         NA      NA             NA
##         tend_crops kill_crops
## Manager         NA         NA
## user_1          NA         NA
## user_2          NA         NA
## user_3          NA         NA
## user_4          NA         NA</code></pre>
<p>Although a second call of <code>gmse_apply</code> has identical initial conditions, because resource demographics (e.g., birth and death) and agent decision making (e.g., policy generation and user actions) is not deterministic, a slightly different result is obtained below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rand_eg_2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_apply.html">gmse_apply</a></span>();
<span class="kw">print</span>(rand_eg_2);</code></pre></div>
<pre><code>## $resource_results
## [1] 1102
## 
## $observation_results
## [1] 1292.517
## 
## $manager_results
##          resource_type scaring culling castration feeding help_offspring
## policy_1             1      NA      60         NA      NA             NA
## 
## $user_results
##         resource_type scaring culling castration feeding help_offspring
## Manager             1      NA       0         NA      NA             NA
## user_1              1      NA      16         NA      NA             NA
## user_2              1      NA      16         NA      NA             NA
## user_3              1      NA      16         NA      NA             NA
## user_4              1      NA      16         NA      NA             NA
##         tend_crops kill_crops
## Manager         NA         NA
## user_1          NA         NA
## user_2          NA         NA
## user_3          NA         NA
## user_4          NA         NA</code></pre>
<p>To make meaningful model inferences, it is often necessary to replicate simulations under the same initial conditions to understand the range of predicted outcomes for a particular set of parameter values. This can be computationally intense, but it can also lead to a more robust understanding of the range of dynamics that might be expected within a system. Additionally, when parameter values are unknown but believed to be important, replicate simulations can be applied across a range of values to understand how a particular parameter might affect system dynamics. Below, we show how to use the <code>gmse_replicates</code> function to simulate a simple example of a managed population that is hunted by users. This function calls <code>gmse</code> multiple times and aggregates the results from replicate simulations into a single table.</p>
<p>For a single simulation, the <code>gmse_table</code> function prints out key information from a <code>gmse</code> simulation result. The example provided in the <a href="https://cran.r-project.org/package=GMSE">GMSE documentation</a> is below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_sim  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse.html">gmse</a></span>(<span class="dt">time_max =</span> <span class="dv">10</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>);</code></pre></div>
<pre><code>## [1] "Initialising simulations ... "</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_table &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_table.html">gmse_table</a></span>(<span class="dt">gmse_sim =</span> gmse_sim);
<span class="kw">print</span>(sim_table)</code></pre></div>
<pre><code>##       time_step resources  estimate cost_culling cost_unused act_culling
##  [1,]         1      1079 1405.8957           57          53          68
##  [2,]         2      1119  884.3537          110           0          36
##  [3,]         3      1221 1587.3016           10         100         309
##  [4,]         4      1065 1269.8413           10         100         400
##  [5,]         5       743  793.6508          110           0          36
##  [6,]         6       927  907.0295          110           0          36
##  [7,]         7      1054  975.0567          110           0          36
##  [8,]         8      1184 1564.6259           10         100         302
##  [9,]         9      1067  952.3810          110           0          36
## [10,]        10      1214  975.0567          110           0          36
##       act_unused harvested
##  [1,]          4        68
##  [2,]          2        36
##  [3,]         90       309
##  [4,]          0       400
##  [5,]          2        36
##  [6,]          2        36
##  [7,]          1        36
##  [8,]         98       302
##  [9,]          2        36
## [10,]          2        36</code></pre>
<p>The above table can be saved as a CSV file using the <code>write.csv</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">write.csv</span>(<span class="dt">x=</span> sim_table, <span class="dt">file =</span> <span class="st">"file_path/gmse_table_name.csv"</span>);</code></pre></div>
<p>Instead of recording all time steps in the simulation, we can instead record only the last time step in <code>gmse_table</code> using the <code>all_time</code> argument.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sim_table_last &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_table.html">gmse_table</a></span>(<span class="dt">gmse_sim =</span> gmse_sim, <span class="dt">all_time =</span> <span class="ot">FALSE</span>);
<span class="kw">print</span>(sim_table_last)</code></pre></div>
<pre><code>##    time_step    resources     estimate cost_culling  cost_unused 
##      10.0000    1214.0000     975.0567     110.0000       0.0000 
##  act_culling   act_unused    harvested 
##      36.0000       2.0000      36.0000</code></pre>
<p>The <code>gmse_replicates</code> function replicates multiple simulations <code>replicates</code> times under the same initial conditions, then returns a table showing the values of all simulations. This can be useful, for example, for testing how frequently a population is expected to go to extinction or carrying capacity under a given set of parameter values. First, we demonstrate the <code>gmse_replicates</code> function for simulations of up to 20 time steps. The <code>gmse_replicates</code> function accepts all arguments used in <code>gmse</code>, and also all arguments of <code>gmse_table</code> (<code>all_time</code> and <code>hide_unused_options</code>) to summarise multiple <code>gmse</code> results. Here we use default <code>gmse</code> values in replicate simulations, except <code>plotting</code>, which we set to <code>FALSE</code> to avoid plotting each simulation result. We run 10 replicates below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_reps1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_replicates.html">gmse_replicates</a></span>(<span class="dt">replicates =</span> <span class="dv">10</span>, <span class="dt">time_max =</span> <span class="dv">20</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>);
<span class="kw">print</span>(gmse_reps1);</code></pre></div>
<pre><code>##       time_step resources  estimate cost_culling cost_unused act_culling
##  [1,]        20      1236  861.6780          108           2          36
##  [2,]        20       736  657.5964          110           0          36
##  [3,]        20       830  680.2721          110           0          36
##  [4,]        20       966  702.9478          110           0          36
##  [5,]        20      1399 1451.2472           10         100         356
##  [6,]        20       765  975.0567          110           0          36
##  [7,]        20      1294 1564.6259           10         100         353
##  [8,]        20       687  544.2177          110           0          36
##  [9,]        20      1248 1247.1655           10         100         302
## [10,]        20      1216 1360.5442           10         100         400
##       act_unused harvested
##  [1,]          4        36
##  [2,]          2        36
##  [3,]          3        36
##  [4,]          2        36
##  [5,]         44       356
##  [6,]          1        36
##  [7,]         47       353
##  [8,]          3        36
##  [9,]         97       302
## [10,]          0       400</code></pre>
<p>Note from the results above that resources in all simulations persisted for 20 time steps, which means that extinction never occurred. We can also see that the population in all simulations never terminated at a density near the default carrying capacity of <code>res_death_K = 2000</code>, and was instead consistently near the target population size of <code>manage_target = 1000</code>. If we wish to define management success as having a population density near target levels after 20 time steps (perhaps interpreted as 20 years), then we might assess this population as successfully managed under the conditions of the simulation. We can then see what happens if managers only respond to changes in the social-ecological system with a change in policy once every two years, perhaps as a consequence of reduced funding for management or increasing demands for management attention elsewhere. This can be done by changing the default <code>manage_freq = 1</code> to <code>manage_freq = 2</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_reps2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_replicates.html">gmse_replicates</a></span>(<span class="dt">replicates  =</span> <span class="dv">10</span>, <span class="dt">time_max =</span> <span class="dv">20</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>, 
                              <span class="dt">manage_freq =</span> <span class="dv">2</span>);
<span class="kw">print</span>(gmse_reps2);</code></pre></div>
<pre><code>##       time_step resources   estimate cost_culling cost_unused act_culling
##  [1,]        20       590  498.86621          110           0          36
##  [2,]        20       745  748.29932          110           0          36
##  [3,]        20       939  929.70522          110           0          36
##  [4,]        20        95   90.70295          110           0          36
##  [5,]        20       748  793.65079          110           0          36
##  [6,]        20      1508 1814.05896           10         100         289
##  [7,]        20       999 1247.16553           10         100         400
##  [8,]        20       325  226.75737          110           0          36
##  [9,]        20      1353 1201.81406           10         100         310
## [10,]        20       745  544.21769          110           0          36
##       act_unused harvested
##  [1,]          4        36
##  [2,]          4        36
##  [3,]          1        36
##  [4,]          3        36
##  [5,]          0        36
##  [6,]        111       289
##  [7,]          0       400
##  [8,]          1        36
##  [9,]         89       310
## [10,]          1        36</code></pre>
<p>Note that while extinction still does not occur in these simulations, when populations are managed less frequently, they tend to be less close to the target size of 1000 after 20 generations. The median population size of <code>gmse_reps1</code> (management in every time step) was 1091, with a maximum of 1399 and minimum of 687. The median population size of the newly simulated <code>gmse_reps2</code> (management every two time steps) is 746.5, with a maximum of 1508 and minimum of 95. We can now see what happens when management occurs only once in every three time steps.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_reps3 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_replicates.html">gmse_replicates</a></span>(<span class="dt">replicates =</span> <span class="dv">10</span>, <span class="dt">time_max =</span> <span class="dv">20</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>, 
                             <span class="dt">manage_freq =</span> <span class="dv">3</span>);
<span class="kw">print</span>(gmse_reps3);</code></pre></div>
<pre><code>##       time_step resources  estimate cost_culling cost_unused act_culling
##  [1,]        20      1157  657.5964          110           0          36
##  [2,]        20      1217 1133.7868           17          93         232
##  [3,]        20       913  612.2449          109           1          36
##  [4,]        20      1158  929.7052          108           2          36
##  [5,]        20      1362  861.6780          109           1          36
##  [6,]        20      1485 2131.5193           10         100         400
##  [7,]        20       214  385.4875          110           0          36
##  [8,]        15         0    0.0000          110           0          36
##  [9,]        20       530  566.8934          110           0          36
## [10,]        20      1736  997.7324          110           0          36
##       act_unused harvested
##  [1,]          4        36
##  [2,]          1       232
##  [3,]          4        36
##  [4,]          4        36
##  [5,]          3        36
##  [6,]          0       400
##  [7,]          2        36
##  [8,]          1         0
##  [9,]          2        36
## [10,]          3        36</code></pre>
<p>Given a management frequency of once every three time steps, the median population size of <code>gmse_reps3</code> (management in every time step) is 1157.5, with a maximum of 1736 and minimum of 0. The number of extinctions observed in these replicate populations was 1. Below we change the management frequency to once every four time steps.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_reps4 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_replicates.html">gmse_replicates</a></span>(<span class="dt">replicates =</span> <span class="dv">10</span>, <span class="dt">time_max =</span> <span class="dv">20</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>, 
                             <span class="dt">manage_freq =</span> <span class="dv">4</span>);
<span class="kw">print</span>(gmse_reps4);</code></pre></div>
<pre><code>##       time_step resources   estimate cost_culling cost_unused act_culling
##  [1,]        20      1986 1746.03175           10         100         339
##  [2,]        20         0    0.00000          110           0          36
##  [3,]         9         0   22.67574          110           0          36
##  [4,]        20       190  204.08163          110           0          36
##  [5,]        19         0 1383.21995           10         100         400
##  [6,]        20       744  544.21769          110           0          36
##  [7,]        20       218  158.73016          108           2          36
##  [8,]        20      1082 1247.16553           10         100         302
##  [9,]        20        62   45.35147          109           1          36
## [10,]        13         0    0.00000          110           0          36
##       act_unused harvested
##  [1,]         60       339
##  [2,]          2         0
##  [3,]          2         0
##  [4,]          4        36
##  [5,]          0         0
##  [6,]          1        36
##  [7,]          6        36
##  [8,]         97       302
##  [9,]          2        36
## [10,]          2         0</code></pre>
<p>Now note from the first column of <code>gmse_reps4</code> above that 3 populations did not persist to the 20th time step; i.e., 4 populations went to extinction (note that GMSE has a minimum resource population size of 5). This has occured because managers cannot respond quickly enough to changes in the population density, and therefore cannot increase the cost of culling to maintain target resource levels if population size starts to decrease. We can see the extinction risk increase even further if management only occurs once every 5 time steps.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gmse_reps5 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gmse_replicates.html">gmse_replicates</a></span>(<span class="dt">replicates =</span> <span class="dv">10</span>, <span class="dt">time_max =</span> <span class="dv">20</span>, <span class="dt">plotting =</span> <span class="ot">FALSE</span>, 
                             <span class="dt">manage_freq =</span> <span class="dv">5</span>);
<span class="kw">print</span>(gmse_reps5);</code></pre></div>
<pre><code>##       time_step resources estimate cost_culling cost_unused act_culling
##  [1,]         5         0        0          109           1          36
##  [2,]         5         0        0          109           1          36
##  [3,]         5         0        0          110           0          36
##  [4,]         5         0        0          108           2          36
##  [5,]         5         0        0          110           0          36
##  [6,]         5         0        0          110           0          36
##  [7,]         5         0        0          109           1          36
##  [8,]         5         0        0          110           0          36
##  [9,]         5         0        0          110           0          36
## [10,]         5         0        0          109           1          36
##       act_unused harvested
##  [1,]          2         0
##  [2,]          1         0
##  [3,]          2         0
##  [4,]          4         0
##  [5,]          3         0
##  [6,]          2         0
##  [7,]          3         0
##  [8,]          3         0
##  [9,]          3         0
## [10,]          3         0</code></pre>
<p>When a manager can only make policy decisions once every five time steps, extinction occurs in 10 out of 10 simulated populations before year 20. If we wanted to summarise these results, we could plot how extinction risk changes with increasing <code>manage_freq</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ext_risk1 &lt;-<span class="st"> </span><span class="kw">sum</span>(gmse_reps1[,<span class="dv">2</span>] &lt;<span class="st"> </span><span class="dv">20</span>);
ext_risk2 &lt;-<span class="st"> </span><span class="kw">sum</span>(gmse_reps2[,<span class="dv">2</span>] &lt;<span class="st"> </span><span class="dv">20</span>);
ext_risk3 &lt;-<span class="st"> </span><span class="kw">sum</span>(gmse_reps3[,<span class="dv">2</span>] &lt;<span class="st"> </span><span class="dv">20</span>);
ext_risk4 &lt;-<span class="st"> </span><span class="kw">sum</span>(gmse_reps4[,<span class="dv">2</span>] &lt;<span class="st"> </span><span class="dv">20</span>);
ext_risk5 &lt;-<span class="st"> </span><span class="kw">sum</span>(gmse_reps5[,<span class="dv">2</span>] &lt;<span class="st"> </span><span class="dv">20</span>);
y_var     &lt;-<span class="st"> </span><span class="kw">c</span>(ext_risk1, ext_risk2, ext_risk3, ext_risk4, ext_risk5);
x_var     &lt;-<span class="st"> </span><span class="dv">1</span>:<span class="dv">5</span>;
<span class="kw">plot</span>(<span class="dt">x =</span> x_var, <span class="dt">y =</span> y_var, <span class="dt">type =</span> <span class="st">"b"</span>, <span class="dt">pch =</span> <span class="dv">20</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">cex =</span> <span class="fl">1.5</span>,
     <span class="dt">xlab =</span> <span class="st">"Management every N time steps (manage_freq)"</span>,
     <span class="dt">ylab =</span> <span class="st">"Freq. of population extinction"</span>, <span class="dt">cex.lab =</span> <span class="fl">1.25</span>)</code></pre></div>
<div class="figure">
<img src="SI6_files/figure-html/unnamed-chunk-22-1.png" alt="Extinction risk given an increasing number of time steps between updating policy decisions for culling costs in a simulated population. Higher values on the x-axis correspond to more time passing before a new policy is set. For each point, a total of 10 replicate simulations were run." width="700"><p class="caption">
Extinction risk given an increasing number of time steps between updating policy decisions for culling costs in a simulated population. Higher values on the x-axis correspond to more time passing before a new policy is set. For each point, a total of 10 replicate simulations were run.
</p>
</div>
<p>The above plot and the simulations from which it was derived illustrates a greatly simplified example of how GMSE might be used to assess the risk of extinction in a managed population. A comprehensive analysis would need more than 10 replicate simulations to accurately infer extinction risk, and would require careful pararmeterisation of all sub-models and a sensitivity analysis where such parameters are unknown. A benefit of this approach is that it allows for the simulation of multiple different scenarios under conditions of uncertainty and stochasticity, modelling the range of outcomes that might occur within and among scenarios and facilitating the development of social-ecological theory. Future expansion on the complexity of individual-based default sub-models of GMSE will further increase the realism of targeted case studies.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-Grimm1999">
<p>Grimm, Volker. 1999. “Ten years of individual-based modelling in ecology: what have we learned and what could we learn in the future?” <em>Ecological Modelling</em> 115 (2-3): 129–48. doi:<a href="https://doi.org/10.1016/S0304-3800(98)00188-4">10.1016/S0304-3800(98)00188-4</a>.</p>
</div>
<div id="ref-Uchmanski1996">
<p>Uchmański, J, and V Grimm. 1996. “Individual-based modelling in ecology: what makes the difference?” <em>Trends in Ecology &amp; Evolution</em> 11 (10): 437–41. <a href="http://www.sciencedirect.com/science/article/pii/0169534796200916" class="uri">http://www.sciencedirect.com/science/article/pii/0169534796200916</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#the-individual-based-approach-of-default-gmse-sub-models">The individual-based approach of default GMSE sub-models</a></li>
      <li><a href="#replicate-simulations-as-a-tool-for-model-inference">Replicate simulations as a tool for model inference</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by A. Bradley Duthie, Nils Bunnefeld.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
