<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Default GMSE data structures • GMSE</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Default GMSE data structures">
<meta property="og:description" content="GMSE">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">GMSE</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.6.0.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/GMSE.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/SI1.html">The Genetic Algorithm of GMSE</a>
    </li>
    <li>
      <a href="../articles/SI2.html">Use of the gmse_apply function</a>
    </li>
    <li>
      <a href="../articles/SI3.html">Example case study in GMSE</a>
    </li>
    <li>
      <a href="../articles/SI4.html">Advanced case study options</a>
    </li>
    <li>
      <a href="../articles/SI5.html">Fisheries example integrating FLR</a>
    </li>
    <li>
      <a href="../articles/SI6.html">Management frequency and extinction risk</a>
    </li>
    <li>
      <a href="../articles/SI7.html">Default GMSE data structures</a>
    </li>
    <li>
      <a href="../articles/SI8.html">Adaptive timing of investment strategy</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://confoobio.github.io/gmse/notebook/gmse_notes.html">Lab notebook</a>
</li>
<li>
  <a href="https://github.com/confoobio/GMSE">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Default GMSE data structures</h1>
            <h3 class="subtitle">GMSE: an R package for generalised management strategy evaluation (Supporting Information 7)</h3>
                        <h4 class="author"><div class="line-block">A. Bradley Duthie¹³, Jeremy J. Cusack¹, Isabel L. Jones¹, Jeroen Minderman¹,<br>
Erlend B. Nilsen², Rocío A. Pozo¹, O. Sarobidy Rakotonarivo¹,<br>
Bram Van Moorter², and Nils Bunnefeld¹</div></h4>
            
            <h4 class="date">[1] Biological and Environmental Sciences, University of Stirling, Stirling, UK [2] Norwegian Institute for Nature Research, Trondheim, Norway [3] <a href="mailto:alexander.duthie@stir.ac.uk" class="email">alexander.duthie@stir.ac.uk</a>
</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/confoobio/gmse/blob/master/vignettes/SI7.Rmd"><code>vignettes/SI7.Rmd</code></a></small>
      <div class="hidden name"><code>SI7.Rmd</code></div>

    </div>

    
    
<div id="the-most-important-default-gmse-data-structures" class="section level1">
<h1 class="hasAnchor">
<a href="#the-most-important-default-gmse-data-structures" class="anchor"></a>The most important (default) GMSE data structures</h1>
<p>The default sub-models of GMSE (<code>resource</code>, <code>observation</code>, <code>manager</code>, and <code>user</code>) use a small number of default data structures to hold the information needed in simulations. While these default sub-models do not necessarily need to be used in every run in GMSE (see <a href="SI2.html">use of</a> <code>gmse_apply</code>), they will be used in any run of the <code>gmse</code> function, and in any call of the <code>gmse_apply</code> function that does not run with entirely custom sub-models. Simulation and model inference do not require an understanding of the default data structures, but such an understanding can be especially useful when running <code>gmse_apply</code> if there is a need to extract uncommonly used information, change key simulated values (e.g., landscape properties, agent budgets, or resource movement rules, as in <a href="SI4.html">Advanced case study options</a>), or build custom individual-based sub-models. Here we provide a brief explanation of the following key data structures (each name below is listed as it is named in the output <code>gmse_apply</code> when <code>get_res = "Full"</code>).</p>
<ol style="list-style-type: decimal">
<li><a href="#agents"><code>AGENTS</code></a></li>
<li>
<a href="#resources"><code>resource_array</code></a> (or <code>RESOURCES</code>)</li>
<li>
<a href="#observation"><code>observation_array</code></a> (or <code>OBSERVATION</code>)</li>
<li>
<a href="#cost"><code>manager_array</code></a> (or <code>COST</code>)</li>
<li>
<a href="#action"><code>user_array</code></a> (or <code>ACTION</code>)</li>
<li><a href="#land"><code>LAND</code></a></li>
</ol>
<p>Note that these are not the only data structures used in GMSE, but they are the only ones that can be easily modified in GMSE (see, e.g., <a href="SI4.html">Advanced case study options</a>), so they are the ones that we focus on here. Additionally, any custom subfunction that returns an array rather than a single value should adhere to the same structure as these defaults if any default GMSE functions are to be used in <code>gmse_apply</code>. We can investigate each data structure by running a single simulation of <code>gmse_apply</code>.</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="no">sim</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/gmse_apply.html">gmse_apply</a></span>(<span class="kw">get_res</span> <span class="kw">=</span> <span class="st">"Full"</span>);</pre></body></html></div>
<p>The full list output of <code>sim</code> holds each structure by name (in the case where two names are used, e.g., <code>resource_array</code> and <code>RESOURCES</code>, both are identical, but the lower case <code>resource_array</code> takes precedence in case of a change). Each data structure can be examined, changed, and incorporated into a new simulation (e.g., <code>new_sim &lt;- gmse_apply(old_list = sim)</code>).</p>
</div>
<div id="agents" class="section level1">
<h1 class="hasAnchor">
<a href="#agents" class="anchor"></a>1. AGENTS</h1>
<p>The <code>AGENTS</code> data structure is a two dimensional array with a fixed number of 27 columns and a number of rows that is always equal to the sum of the number of manager and users (i.e., each row is an individual agent).</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">AGENTS</span>);</pre></body></html></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]    1    0    0    0   49   20   50    0   10     0    43     0     0 10000
## [2,]    2    1    0    0   96   19   50    0   10     0     0     0     0     0
## [3,]    3    1    0    0   19   26   50    0   10     0     0     0     0     0
## [4,]    4    1    0    0    2   77   50    0   10     0     0     0     0     0
## [5,]    5    1    0    0    9   13   50    0   10     0     0     0     0     0
##      [,15]  [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
## [1,]     0 9508.5  1000     0 -1.17     0     0     0     0     0     0     0
## [2,]     0    0.0  1000     0 -1.30     0     0     0     0     0     0     0
## [3,]     0    0.0  1000     0 -1.30     0     0     0     0     0     0     0
## [4,]     0    0.0  1000     0 -1.30     0     0     0     0     0     0     0
## [5,]     0    0.0  1000     0 -1.30     0     0     0     0     0     0     0
##      [,27]
## [1,]     0
## [2,]     0
## [3,]     0
## [4,]     0
## [5,]     0</code></pre>
<p>In the default case above, there are five agents (one manager and four users), each represented by a unique row. Columns in the array represent the agent traits listed below.</p>
<ol style="list-style-type: decimal">
<li>ID (each agent gets a unique number)</li>
<li>Type 1 (0 indicates the manager; 1 indicates users)</li>
<li>Type 2 (currently unused)</li>
<li>Type 3 (currently unused)</li>
<li>x-location on the landscape (typically ignored)</li>
<li>y-location on the landscape (typically ignored)</li>
<li>Movement distance (typically ignored)</li>
<li>Time parameter (typically ignored)</li>
<li>Distance of vision (currently used only for managers)</li>
<li>Error parameter (currently unused)</li>
<li>Resource marking parameter (currently used only for managers)</li>
<li>Resource tally parameter (currently used only for managers)</li>
<li>How many resources an agent has in view (unused)</li>
<li>Total number of cells owned by an agent</li>
<li>Unused column</li>
<li>Yield from owned land (zero for users when default <code>land_ownership = FALSE</code>)</li>
<li>Agent’s baseline budget</li>
<li>Agent’s perception of the efficacy of scaring one resource</li>
<li>Agent’s perception of the efficacy of culling one resource</li>
<li>Agent’s perception of the efficacy of castrating one resource</li>
<li>Agent’s perception of the efficacy of feeding one resource</li>
<li>Agent’s perception of the efficacy of helping offspring of one resource</li>
<li>Agent’s perception of the efficacy of tending the crop on one landscape cell</li>
<li>Agent’s perception of the efficacy of killing the crop on one landscape cell</li>
<li>Increment added to the manager’s (row 1) baseline budget caused by a budget bonus</li>
<li>Increment added to an agent’s budget caused by yield</li>
<li>Unused column</li>
</ol>
<p>Note that for the perceptions of the efficacy of different actions (columns 18-24), this relates to whatever it is that the agents are acting upon. For example, for columns 18-22, actions are on the resources, so if an agent’s perception of the efficacy of scaring is -1, this means that they believe that scaring a resource will decrease the number of resources affecting them by 1 (lower default values for landowners are caused based on the probability of a scared resource landing on a different cell owned by the same agent). For columns 23-24, actions are on the landscape, so if an agent tends the crop on one landscape cell, this value defines an agent’s perception of how much yield on that cell will increase.</p>
<p>It is obvious from the above list that several columns represent traits that are either typically ignored or currently not in use. This is intended to allow for easier future development of default model options and potential customisation of sub-models in <code>gmse_apply</code>. We anticipate that future versions of GMSE will contain multiple user types with unique traits and among-user interactions.</p>
</div>
<div id="resources" class="section level1">
<h1 class="hasAnchor">
<a href="#resources" class="anchor"></a>2. resource_array</h1>
<p>The <code>resource_array</code> (also accessible as <code>RESOURCES</code>) is a two dimensional array with a fixed number of 22 columns and a number of rows that is always equal to the total number of resources (each row is an individual resource). In the above simulation, <code>sim$resource_array</code> includes 1094 rows, so we only print out the first eight for illustration.</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">resource_array</span>[<span class="fl">1</span>:<span class="fl">8</span>,]);</pre></body></html></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]    1    1    0    0   41   19   20    1    0   0.3     0     3     0     0
## [2,]    3    1    0    0   25    8   20    1    0   0.3     0     2     0     0
## [3,]    5    1    0    0   10   25   20    1    0   0.3     0     5     0     0
## [4,]    6    1    0    0   57   30   20    1    0   0.3     0     4     0     0
## [5,]    7    1    0    0   10    3   20    1    0   0.3     0     5     0     0
## [6,]    8    1    0    0   29   70   20    1    0   0.3     0     5     0     0
## [7,]   10    1    0    0   93   91   20    1    0   0.3     0     4     0     0
## [8,]   13    1    0    0   62   15   20    1    0   0.3     0     2     0     0
##      [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22]
## [1,]   0.5     0     0     0     0     0     0     1
## [2,]   0.5     0     0     0     0     0     0     1
## [3,]   0.5     0     0     0     0     0     0     1
## [4,]   0.5     0     0     0     0     0     0     1
## [5,]   0.5     0     0     0     0     0     0     1
## [6,]   0.5     0     0     0     0     0     0     1
## [7,]   0.5     0     0     0     0     0     0     1
## [8,]   0.5     0     0     0     0     0     0     1</code></pre>
<p>Columns in the resource array represent the individual resource traits listed below.</p>
<ol style="list-style-type: decimal">
<li>ID (each resource gets a unique number)</li>
<li>Type 1 (currently all resources are of type 1)</li>
<li>Type 2 (currently unused)</li>
<li>Type 3 (currently unused)</li>
<li>x-location on the landscape</li>
<li>y-location on the landscape</li>
<li>Movement distance</li>
<li>Time parameter (typically ignored)</li>
<li>Density-independent removal (i.e., death) probability</li>
<li>Growth (i.e., birth) probability</li>
<li>Offspring produced</li>
<li>Age (initial resources are given a random age between 1 and the maximum age sampled from a uniform distribution; offspring always start at age zero in their time step of birth)</li>
<li>Marking indicator (used in the observation function)</li>
<li>Tallying indicator (used in the observation function)</li>
<li>Proportion of a landscape cell the resource consumes in a time step</li>
<li>Has the resource been scared by an agent?</li>
<li>Has the resource been culled by an agent?</li>
<li>Has the resource been castrated by an agent?</li>
<li>Has the resource’s growth rate been increased by an agent?</li>
<li>Has the resource’s offspring production been increased by an agent?</li>
<li>How much yield has the resource consumed?</li>
<li>How many times can the resource consume yield in one time step?</li>
</ol>
<p>In the case of columns 16-20, the value is either zero (if no action has occurred), or some positive integer that matches the ID of the agent that has performed the act (e.g., if column 17 equals 3, then that means that the agent with ID = 3 culled the resource in the corresponding row; where more than one agent’s action is possible per time step – as in scaring – the integer reflects the most recently acting agent). We anticipate that future versions of gmse will contain multiple resource types, and might add columns to include additional resource traits.</p>
</div>
<div id="observation" class="section level1">
<h1 class="hasAnchor">
<a href="#observation" class="anchor"></a>3. observation_array</h1>
<p>The <code>observation_array</code> (also accessible as <code>OBSERVATION</code>) is a two dimensional array, the number of rows and columns of which depend on the type of observation being made (i.e., <code>observe_type</code>, which can take integer values from 0-3; see the <a href="https://cran.r-project.org/package=GMSE">GMSE reference manual</a> for more information about built-in observation types that are available in GMSE). The first 20 columns of <code>observation_array</code> contain the same individual resource traits as in <code>resource_array</code>, while any additional columns provide information about how and when a resource was observed. The number of rows in <code>observation_array</code> is always equal to or less than that of <code>resource_array</code>; each resource that is observed at least once is placed into one unique row, while unobserved resources are not included as rows in the <code>observation_array</code>. In <code>sim</code>, there are 43 rows, meaning that 1051 resources were not observed at all in this time step. Below, we print out the first eight rows of the observation array.</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">observation_array</span>[<span class="fl">1</span>:<span class="fl">8</span>,]);</pre></body></html></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]    1    1    0    0   41   19   20    1    0   0.3     0     3     1     0
## [2,]    6    1    0    0   57   30   20    1    0   0.3     0     4     1     0
## [3,]   31    1    0    0   42   11   20    1    0   0.3     0     4     1     0
## [4,]   39    1    0    0   51   10   20    1    0   0.3     0     3     1     0
## [5,]   47    1    0    0   59   11   20    1    0   0.3     1     5     1     0
## [6,]   49    1    0    0   47   11   20    1    0   0.3     2     4     1     0
## [7,]  115    1    0    0   47   26   20    1    0   0.3     0     2     1     0
## [8,]  164    1    0    0   50   26   20    1    0   0.3     0     2     1     0
##      [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24]
## [1,]   0.5     0     0     0     0     0     0     1     0     1
## [2,]   0.5     0     0     0     0     0     0     1     0     1
## [3,]   0.5     0     0     0     0     0     0     1     0     1
## [4,]   0.5     0     0     0     0     0     0     1     0     1
## [5,]   0.5     0     0     0     0     0     0     1     0     1
## [6,]   0.5     0     0     0     0     0     0     1     0     1
## [7,]   0.5     0     0     0     0     0     0     1     0     1
## [8,]   0.5     0     0     0     0     0     0     1     0     1</code></pre>
<p>In the case of the default parameters, the observation array has only two additional columns; the first added column 21 is currently unused, and all values in this column are zero. The second added column 22 contains a value of 1 confirming that the resource was observed. Additional options will add different numbers of columns with different values. For example, when <code>observe_type = 0</code> (managers observe all resources on a random subset of the landscape, the size of which is determined by their distance of vision) but <code>times_observe &gt; 1</code>, managers sample more than one random subset of the landscape. A new column is added for each sampled subset, and a 1 is placed in the relevant column if the resource is observed (these collected data are then used to estimate population size). An example where <code>times_observe = 4</code> is shown below.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="no">sim_t0_4</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/gmse_apply.html">gmse_apply</a></span>(<span class="kw">get_res</span> <span class="kw">=</span> <span class="st">"Full"</span>, <span class="kw">times_observe</span> <span class="kw">=</span> <span class="fl">4</span>);
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim_t0_4</span>$<span class="no">observation_array</span>[<span class="fl">1</span>:<span class="fl">8</span>,]);</pre></body></html></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]    8    1    0    0   37   71   20    1    0   0.3     1     2     1     0
## [2,]    9    1    0    0   47   64   20    1    0   0.3     0     4     1     0
## [3,]   10    1    0    0   71   94   20    1    0   0.3     0     5     1     0
## [4,]   13    1    0    0   43   80   20    1    0   0.3     1     3     1     0
## [5,]   16    1    0    0   73   89   20    1    0   0.3     0     5     1     0
## [6,]   22    1    0    0   77   84   20    1    0   0.3     1     4     1     0
## [7,]   31    1    0    0   80   21   20    1    0   0.3     0     3     1     0
## [8,]   33    1    0    0   81   18   20    1    0   0.3     0     5     1     0
##      [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
## [1,]   0.5     0     0     0     0     0     0     1     0     0     0     1
## [2,]   0.5     0     0     0     0     0     0     1     0     0     0     1
## [3,]   0.5     0     0     0     0     0     0     1     0     1     0     0
## [4,]   0.5     0     0     0     0     0     0     1     0     0     0     1
## [5,]   0.5     0     0     0     0     0     0     1     0     1     0     0
## [6,]   0.5     0     0     0     0     0     0     1     0     0     1     0
## [7,]   0.5     0     0     0     0     0     0     1     0     0     0     0
## [8,]   0.5     0     0     0     0     0     0     1     0     0     0     0
##      [,27]
## [1,]     0
## [2,]     0
## [3,]     0
## [4,]     0
## [5,]     0
## [6,]     0
## [7,]     1
## [8,]     1</code></pre>
<p>This process simulates the data collection of resources (and potentially resource trait measurement) as might be performed by observers within the system. It therefore takes a virtual ecologist approach; this enables the integration of theory and empirical work and can improve the mechanistic understanding of social-ecological systems <span class="citation">(Zurell et al. <a href="#ref-Zurell2010">2010</a>)</span>.</p>
</div>
<div id="cost" class="section level1">
<h1 class="hasAnchor">
<a href="#cost" class="anchor"></a>4. manager_array</h1>
<p>For context, it might be easier to understand <code>manager_array</code> after reading about <code>user_array</code> <a href="#action">below</a>. The <code>manager_array</code> (also accessible as <code>COST</code>) is a three dimensional array, each layer of which corresponds to a unique agent (rows in <a href="#agents"><code>AGENT</code></a> correpond to layers in <code>manager_array</code>). Hence, in the simulation output <code>sim$manager_array</code>, there are 5 layers. Each layer in <code>manager_array</code> has 13 columns, and a number of rows that varies depending on the number of agents and resource types. As of GMSE v0.4.0.7, only the first three rows are used. Two layers of <code>sim$manager_array</code> are shown below, the first being that of the manager and the second being that of the first user.</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">manager_array</span>[,,<span class="fl">1</span>:<span class="fl">2</span>]);</pre></body></html></div>
<pre><code>## , , 1
## 
##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]   [,8]   [,9]  [,10]
## [1,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [2,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [3,] 100001 100001 100001 100001 100001 100001 100001 100001     10 100001
## [4,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [5,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [6,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [7,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
##       [,11]  [,12]  [,13]
## [1,] 100001 100001     10
## [2,] 100001 100001     10
## [3,] 100001 100001     10
## [4,] 100001 100001 100001
## [5,] 100001 100001 100001
## [6,] 100001 100001 100001
## [7,] 100001 100001 100001
## 
## , , 2
## 
##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]   [,8]   [,9]  [,10]
## [1,] 100001 100001 100001 100001 100001 100001 100001 100001     62 100001
## [2,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [3,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [4,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [5,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [6,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
## [7,] 100001 100001 100001 100001 100001 100001 100001 100001 100001 100001
##       [,11]  [,12]  [,13]
## [1,] 100001 100001     10
## [2,] 100001 100001     10
## [3,] 100001 100001 100001
## [4,] 100001 100001 100001
## [5,] 100001 100001 100001
## [6,] 100001 100001 100001
## [7,] 100001 100001 100001</code></pre>
<p>Each element in the array indicates the cost of performing a particular action. In the code, this is the cost of changing an element in <a href="#action"><code>user_array</code></a> (which has the same dimensions as <code>manager_array</code>). The minimum value in <code>sim$manager_array</code> is therefore 10, reflecting the default <code>minimum_cost</code> value of 10. The maximum value is 100001, which is one higher than the maximum allowed manager or user budget. Where a cost is 100001, actions can therefore never be performed. An explanation of the rows and columns of <code>manager_array</code> is provided <a href="#action">below</a> in the description of <code>user_array</code>.</p>
</div>
<div id="action" class="section level1">
<h1 class="hasAnchor">
<a href="#action" class="anchor"></a>5. user_array</h1>
<p>The <code>user_array</code> (also accessible as <code>ACTION</code>) is a three dimensional array, each layer of which corresponds to a unique agent. When considering the three dimensional <code>user_array</code>, it is helpful to keep in mind that each layer corresponds to the actions of a particular agent, that each column corresponds to a particular type of action, and that each row corresponds to a particular resource, agent, or group that the action will affect. The cost of performing any action in this array is held in <a href="#cost"><code>manager_array</code></a>, wherein an action’s cost in <code>manager_array</code> is held in the same array element as the action itself in <code>user_array</code>. Recall from the <a href="#cost">manager array</a> that the first layer of <code>user_array</code> corresponds to the manager actions, and that remaining layers correspond to user actions; there are therefore as many layers in <code>user_array</code> as there are agents in the model, and each row of <a href="#agents"><code>AGENTS</code></a> corresponds to equivalent layer of <code>user_array</code> (e.g., the manager agent, ID = 1, is in the first row of <code>AGENTS</code> and the first layer of <code>user_array</code>). The first two layers of <code>user_array</code> are shown below.</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">user_array</span>[,,<span class="fl">1</span>:<span class="fl">2</span>]);</pre></body></html></div>
<pre><code>## , , 1
## 
##      [,1] [,2] [,3] [,4]       [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
## [1,]   -2    1    0    0 1000.00000    0    0    0    0     0     0     0     0
## [2,]   -1    1    0    0    0.00000    0    0    0    0     0     0     0     0
## [3,]    1    1    0    0   24.94331    0    0   10   62    10    10    10    58
## [4,]    2    1    0    0    0.00000    0    0    0    0     0     0     0     0
## [5,]    3    1    0    0    0.00000    0    0    0    0     0     0     0     0
## [6,]    4    1    0    0    0.00000    0    0    0    0     0     0     0     0
## [7,]    5    1    0    0    0.00000    0    0    0    0     0     0     0     0
## 
## , , 2
## 
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
## [1,]   -2    1    0    0   -1    0    0    0   16     0     0     0     0
## [2,]   -1    1    0    0    0    0    0    0    0     0     0     0     0
## [3,]    1    1    0    0    0    0    0    0    0     0     0     0     0
## [4,]    2    1    0    0    0    0    0    0    0     0     0     0     0
## [5,]    3    1    0    0    0    0    0    0    0     0     0     0     0
## [6,]    4    1    0    0    0    0    0    0    0     0     0     0     0
## [7,]    5    1    0    0    0    0    0    0    0     0     0     0     0</code></pre>
<p>Note that there are more columns in this array than there are possible actions in GMSE. This is because there are several columns that do not map to actions per se, but properties of agents. As of GMSE v0.4.0.7, these properties cannot be changed by other agents. Column of <code>user_array</code> are as follows.</p>
<ol style="list-style-type: decimal">
<li>The type of agent or resource being affected by an action. A value of -2 indicates that actions have a direct effect on a resource (e.g., scaring, culling, etc.). A value of -1 indicates that actions have a direct effect on a landscape layer. Positive integer values indicate actions that affect other agents, where each integer corresponds to the agents’ IDs. Where the integer value is identical with the agent’s own ID (e.g., row 3 in layer 1 where the element <code>sim$user_array[3, 1, 1] = 1</code>), actions affect all other agents in the model. As of GMSE v0.4.0.7, all rows except 1-3 are unused because agents do not affect one anothers actions individually; they either affect all other agents’ actions indiscriminately (in the case of the manager setting policy) or do not (directly) affect other agents’ actions at all (in the case of users). This data structure, however, is designed so that future versions of GMSE will allow users to affect one another directly (representing, e.g., different groups of agents lobbying for different interests, among-user conflict, etc.).</li>
<li>Type 1 of the agent or resource of interest (in practice, this is currently unused).</li>
<li>Type 2 of the agent or resource of interest (currently unused).</li>
<li>Type 3 of the agent or resource of interest (currently unused).</li>
<li>Utility associated with the recipient of the action. For example, in the case of the resource (row 1), positive values indicate that the agent wants more of these resources, while negative values indicate that the agent wants fewer. In the case of the manager (layer 1), the value in the first row equals <code>manage_target</code>, while the value in the third row is the change in resource number needed to achieve the target value (i.e., <code>manage_target =</code> 1000, and the manager’s estimate is <code>sim$observation_vector =</code> 975.0566893. The former minus the latter is 24.94331).</li>
<li>Whether or not the utility associated with the recipient of the action is dependent upon that recipient being on land owned by the actor (e.g., if users only care about resources on landscape cells that they own, then this value is 1 instead of 0).</li>
<li>Whether or not actions on the recipient are possible if the recipient is not on land owned by the actor (e.g., if users cannot cull resources that are not on their own land, then this value is 1 instead of 0).</li>
<li>The number of actions performed for scaring, which in row 3 of the manager layer 1 is interpreted as the scaring cost set by the manager for users.</li>
<li>The number of actions performed for culling, which in row 3 of the manager layer 1 is interpreted as the culling cost set by the manager for users.</li>
<li>The number of actions performed for castration, which in row 3 of the manager’s layer 1 is interpreted as the castration cost set by the manager for users. Further, in row 2 for users (where column 1 equals -1), this value is instead the number of <code>tend_crop</code> actions (the number of cells on which crops are tended by users, which always is perfomed on users’ own land, cannot be affected by the manager, and always equals <code>minimum_cost</code>).</li>
<li>The number of actions performed for feeding resources (increasing their growth rate, <code>lambda</code>), which in row 3 of the manager’s layer 1 is interpreted as the feeding cost set by the manager for users. Further, in row 2 for users (where column 1 equals -1), this value is instead the number of <code>kill_crop</code> actions (the number of cells on which crops are destroyed by users, which always is perfomed on users’ own land, cannot be affected by the manager, and always equals <code>minimum_cost</code>)</li>
<li>The number of actions performed for helping resource offspring (directly increasing offspring production), which in row 3 of the manager’s layer 1 is interpreted as the helping offspring cost set by the manager for users.</li>
<li>The number of actions unspent by the user or manager; any actions allocated to this row do nothing. These may be used when any action would lead the agent to a less than desirable outcome, such as if only culling exists as a policy option (default), but managers do not want to increase the cost of culling because resource density is above <code>manage_target</code>.</li>
</ol>
<p>In the <a href="SI1.html">genetic algorithm</a>, values in elements of a <code>user_array</code> layer are potentially modified according to each agent’s objective, as constrained by costs in <code>manager_array</code>.</p>
</div>
<div id="land" class="section level1">
<h1 class="hasAnchor">
<a href="#land" class="anchor"></a>6. LAND</h1>
<p>Events in default GMSE sub-models occur on a spatially-explicit landscape <code>LAND</code>, which is stored as a three dimensional array. The size of this landscape is specified with the <code>land_dim_1</code> and <code>land_dim_2</code> arguments of GMSE, which determine the length, in cells, of the y and x dimensions of the landscape, respectively (e.g., if <code>land_dim_1 = 10</code> and <code>land_dim_2 = 1000</code>, then the landscape will be one very long horizontal transect). The total number of landscape cells on which resources and agents can interact is therefore the product of <code>land_dim_1</code> and <code>land_dim_2</code>. In addition, all landscapes have three layers, which hold three separate values of information for each x-y location. The first layer is unused as of GMSE v0.6.0.4; the second layer holds crop production on a cell, and the third layer holds the owner of the cell (corresponding to the ID of an agent, where the manager’s ID = 0 defines public land). An <span class="math inline">\(8 \times 8\)</span> portion of the landscape from <code>sim</code> is shown below.</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span>(<span class="no">sim</span>$<span class="no">LAND</span>[<span class="fl">1</span>:<span class="fl">8</span>,<span class="fl">1</span>:<span class="fl">8</span>,]);</pre></body></html></div>
<pre><code>## , , 1
## 
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
## [1,]    1    1    1    1    1    1    1    1
## [2,]    1    1    1    1    1    1    1    1
## [3,]    1    1    1    1    1    1    1    1
## [4,]    1    1    1    1    1    1    1    1
## [5,]    1    1    1    1    1    1    1    1
## [6,]    1    1    1    1    1    1    1    1
## [7,]    1    1    1    1    1    1    1    1
## [8,]    1    1    1    1    1    1    1    1
## 
## , , 2
## 
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
## [1,]    1  1.0 0.25    1    1  1.0  0.5  1.0
## [2,]    1  1.0 1.00    1    1  1.0  1.0  1.0
## [3,]    1  1.0 1.00    1    1  1.0  1.0  0.5
## [4,]    1  1.0 1.00    1    1  1.0  1.0  0.5
## [5,]    1  0.5 1.00    1    1  1.0  1.0  1.0
## [6,]    1  0.5 1.00    1    1  0.5  1.0  1.0
## [7,]    1  1.0 1.00    1    1  0.5  1.0  1.0
## [8,]    1  1.0 1.00    1    1  1.0  1.0  1.0
## 
## , , 3
## 
##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
## [1,]    1    1    1    1    1    1    1    1
## [2,]    1    1    1    1    1    1    1    1
## [3,]    1    1    1    1    1    1    1    1
## [4,]    1    1    1    1    1    1    1    1
## [5,]    1    1    1    1    1    1    1    1
## [6,]    1    1    1    1    1    1    1    1
## [7,]    1    1    1    1    1    1    1    1
## [8,]    1    1    1    1    1    1    1    1</code></pre>
<p>In the case of the above, all of the cells in this square patch of landscape are owned by agent 1 (i.e., the manager; see <code>sim$LAND[,,3]</code>). This occurs if <code>land_ownership = FALSE</code> and users are prohibited from owning land. We can also see that crop production on this patch of land has been decreased from its initialised value of 1 in several cells as a consequence of consumption by resources (see <code>sim$LAND[„2]</code>). By default, landscape yield starts each time step at a value of 1, and hence replenishes in each time even if consumed in the previous time step. Users that own landscape cells (when <code>land_ownership = TRUE</code>) can increase yield above 1 using the <code>tend_crop_yld</code> action. If resources consume landscape yield, the value of yield can drop to a minimum value of zero.</p>
<div id="default-land-distribution-algorithm" class="section level3">
<h3 class="hasAnchor">
<a href="#default-land-distribution-algorithm" class="anchor"></a>6.1. Default land distribution algorithm</h3>
<p>In <a href="SI4.html">Advanced case study options</a>, we show how landscape cell values can be manipulated to customise the placement of land ownership. By default, GMSE v0.6+ places the ownership of landscape cells using a shortest-splitline algorithm (see the lab notebook for <a href="https://confoobio.github.io/gmse/notebook/gmse_notes.html#u-10-MAY-2020">a detailed explanation</a>). The algorithm splits the landscape evenly into smaller and smaller rectangles until a sufficient number of rectangles are produced for all users to own a similar amount of land (note that how uniformly land is partitioned among users will naturally be influenced by how evenly the total number of landscape cells can be divided among them). Below is an example in which land of <code>land_dim_1 = 64</code> and <code>land_dim_2 = 64</code> is partitioned equally among eight users.</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-10-1.png" width="480"></p>
<p>Note that all users own exactly 512 cells on the landscape. A bit more complexity can be generated by an uneven landscape of <code>land_dim_1 = 80</code> and <code>land_dim_2 = 100</code>, with land allocated among nine users.</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-11-1.png" width="480"></p>
<p>In the case of the above landscape, the number of cells allocated to each user ranges from 864 to 920.</p>
</div>
<div id="varying-land-ownership-ownership_var" class="section level3">
<h3 class="hasAnchor">
<a href="#varying-land-ownership-ownership_var" class="anchor"></a>6.2. Varying land ownership: <code>ownership_var</code>
</h3>
<p>In addition, <a href="SI4.html">whereas in previous versions variable landscape ownership among users had to be customised using <code>gmse_apply</code></a>, GMSE v. 0.6+ now includes an additional parameter <code>ownership_var</code>, which takes effect when <code>land_ownership = TRUE</code>. The value of this parameter is expected to be &gt;=0 and &lt;1. At its default value of 0, land ownership is equal among users as demonstrated in the code above. Values &gt;0 increase the extent of variability of landownership among users; in technical terms, <code>ownership_var</code> controls the extent to which each split in the shortest-splitline algorithm is proportional to the number of users the landscape is to be divided into, with larger numbers shifting the split away from even distribution. In practical terms, this means that increasing values of <code>ownership_var</code> produce more unevenly distributed landscapes among users. For example, a value of <code>ownership_var = 0.1</code> produces a relatively limited about of inequity in landscape distribution among users.</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-12-1.png" width="960"> As can be seen from the frequency distribution, in this case, all users own between 1% and 4.3% of the landscape.</p>
<p>By contrast, when increasing <code>ownership_var</code> to 0.8, overall inequity increases substantially:</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-13-1.png" width="960"></p>
<p>In the latter case, user ownership varies between &lt;0.001% and 16.7%.</p>
<p>It should be noted that it is still entirely possible for the user to customise landscapes to whatever extent necessary, using custom <code>gmse_apply</code> loops <a href="SI4.html">as described previously</a>; however, the new <code>ownership_var</code> provides an option in GMSE to alter landscape ownership in a relatively straightforward way.</p>
</div>
<div id="public-land" class="section level3">
<h3 class="hasAnchor">
<a href="#public-land" class="anchor"></a>6.3. Public land</h3>
<p>Public land is placed on the landscape whenever <code>public_land &gt; 0</code>, with <code>public_land</code> defining the proportion of landscape cells that are not be owned by an user. When the expected number of cells to be allocated to public land is calculated to be equal to or greater than that allocated to a single user, public land is allocated in a block as is with users. For example, the below shows a landscape in which <code>public_land = 0.5</code>, with seven other users owning land.</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-14-1.png" width="480"></p>
<p>Public land is in dark blue above. If, however, the amount of public land is very small, the land is added to the centre of the landscape. Below illustrates a landscape that also includes seven land owning users, but with <code>public_land = 0.05</code>.</p>
<p><img src="SI7_files/figure-html/unnamed-chunk-15-1.png" width="480"></p>
<p>Where <code>public_land</code> is small, the default landscape ownership algorithm thereby attempts to be as precise as possible in allocating cell numbers. Of course, as previously mentioned, ownership can also be manually specified when using <code>gmse_apply</code>.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1 class="hasAnchor">
<a href="#conclusions" class="anchor"></a>Conclusions</h1>
<p>We have focused on the data structures <a href="#agents"><code>AGENTS</code></a>, <a href="#resources"><code>resource_array</code></a>, <a href="#observation"><code>observation_array</code></a>, <a href="#cost"><code>manager_array</code></a>, <a href="#action"><code>user_array</code></a>, and <a href="#land"><code>LAND</code></a> because these are the data structures that can be most readily manipulated to customise GMSE simulations. An example of how to do this within a loop using <code>gmse_apply</code> can be found in <a href="SI4.html">Advanced case study options</a>. While other data structures exist within GMSE (e.g., see the output of <code>gmse_apply</code> when <code>get_res = "Full"</code>), we do not recommend manipulating these structures for custom simulations.</p>
<p>Many data structures contain elements that are unused in GMSE v0.6, and in all cases this is designed for ease of ongoing development of new GMSE features. Requests for new features can be made on GitHub using the <a href="https://github.com/bradduthie/gmse/wiki">GMSE Wiki</a> or the <a href="https://github.com/bradduthie/gmse/issues">GMSE Issues</a> page.</p>
</div>
<div id="reference" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#reference" class="anchor"></a>Reference</h1>
<div id="refs" class="references">
<div id="ref-Zurell2010">
<p>Zurell, Damaris, Uta Berger, Juliano S Cabral, Florian Jeltsch, Christine N Meynard, Tamara Münkemüller, Nana Nehrbass, et al. 2010. “The virtual ecologist approach: Simulating data and observers.” <em>Oikos</em> 119 (4): 622–35. <a href="https://doi.org/10.1111/j.1600-0706.2009.18284.x">https://doi.org/10.1111/j.1600-0706.2009.18284.x</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by A. Bradley Duthie, Nils Bunnefeld.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
